title = "Douglas Crescent Gardens Association"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[[menu.navbar]]
    name = "Home"
    weight = 1
    identifier = "index.html"
    url = "/"
[[menu.navbar]]
    name = "News"
	parent = ""
	identifier = "news"
    weight =2
    url = "/news/"
[[menu.navbar]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"	
[[menu.navbar]]
    name = "Contact"
	parent = ""
    weight = 4
    url = "/contact-us/"
[[menu.navbar]]
    name = "Rules And Policies"
	parent = "about"
	identifier = "rules-and-policies"
    weight = 6
    url = "/about/rules-and-policies/"
[[menu.navbar]]
    name = "Trees"
	parent = "about"
    weight = -200
    url = "/about/management-maintenance/"
[[menu.navbar]]
    name = "History & Description"
	parent = "about"
    weight = 7
    url = "/about/description/"
[[menu.navbar]]
    name = "Management & Maintenance"
	parent = "about"
	identifier = "management-and-maintenance"
    weight = 8
    url = "/about/management-and-maintenance/"
[[menu.navbar]]
    name = "Nature notes"
	parent = "about"
    weight = 9
    url = "/about/nature-notes/"
[[menu.navbar]]
    name = "Neighbourhood Matters"
	parent = "about"
	identifier = "neighbourhood-matters"
    weight = 13
    url = "/about/neighbourhood-matters/"
[[menu.navbar]]
    name = "Useful Links"
	parent = "about"
    weight = 14
    url = "/about/useful-links/"	
	


	
	

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["dcga.css"]
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
